### ISSUE TITLE
Previous guidelines and design documentation

### ISSUE THREAD

**Issue by jkosem** [ipfs/browser-design-guidelines#15]
@autonome The folders of things you said you had

**Comment by jkosem** [comment]
@autonome Also, the Consensys decentralised application guidelines if you can dig them up

**Comment by autonome** [comment]
Existing work in this area, related to our goals:

* [Data Permissions Catalog](https://catalogue.projectsbyif.com/) - "An evolving collection of design patterns for sharing data"
* [IDEO Cybersecurity Visuals Challenge](https://challenges.openideo.com/challenge/cybersecurity-visuals/top-ideas) - "reimagining visuals for cyber-security", winning work in the [finalist catalog (PDF)](https://uploads-ssl.webflow.com/5a147545b687370001bfd10c/5db1332e083f4b96b09f9b7f_Cybersecurity%20Visuals%20Challenge%20Finalist%20Catalog.pdf)
* [Consensys Rimble Design System](https://consensys.design/design-system) - "adaptable components and design standards for decentralized applications"

**Comment by jkosem** [comment]
Reckon the direction of Rimble is our best bet in format and approach.
