### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by jkosem** [ipfs/browser-design-guidelines#28]
@autonome Not an absolute must, but if you had any personas or any such work lying around that PL has already done, it would be good to go through them in creating the research questions for interviews.

**Comment by autonome** [comment]
[ipfs-docs-personas.pdf](https://github.com/ipfs/browser-design-guidelines/files/3833906/ipfs-docs-personas.pdf)

**Comment by autonome** [comment]
attached!

**Comment by jkosem** [comment]
Cool thanks. Helps trying to come up with people to do the non-expert (or rather non-super-expert) interviews.
