### ISSUE TITLE
Assumption mapping

### ISSUE THREAD

**Issue by jkosem** [ipfs/browser-design-guidelines#34]

**Comment by jkosem** [comment]
https://www.youtube.com/watch?v=PyCvsBrKO4w

Possible for after design phase done

**Comment by ericronne** [comment]
This exercise could be useful for multiple PL projects :)

**Comment by jkosem** [comment]
Yeah it's a good one. Well actually all of thse would work probably for PL projects/products.

**Comment by jkosem** [comment]
@autonome This one would be great for a lot of things, not just browser design guidelines, but out of scope for this project so closing

Would be a good kickoff for any additional next phases.
