### ISSUE TITLE
Stakeholder(s) Workshop 2

### ISSUE THREAD

**Issue by jkosem** [ipfs/browser-design-guidelines#47]

**Comment by jkosem** [comment]
@autonome I think it would be good if we made the review session Thursday a workshop-esque session to go through deciding on the design direction for sure.

It would go like this:
- 10min of presenting [key themes and findings](https://github.com/ipfs/browser-design-guidelines/blob/master/README.md#research-findings-and-themes)
- No conversation allowed, but while listening to the key themes and findings read out, you should write down what resonates with you as (1) reasons to design it, and (2) what they hear as reasons to not design it, on red sticky notes.
- The post-its are placed all in one area in two big columns. if there are too many reds, you can probably stop here
- Vote/prioritise each, 1. by importance, 2. will be biggest challenges
- Depending on the circumstances you could place the top voted on an effort/impact scale
- Let everyone individually speak their opinion on whether it should be done or not

What do you think?

**Comment by ericronne** [comment]
Would love to crash this!

**Comment by jkosem** [comment]
What do you think @autonome ?

**Comment by jkosem** [comment]
Another way of doing this potentially is to start with [Key design and user context questions and issues](https://github.com/ipfs/browser-design-guidelines/blob/master/README.md#key-design-and-user-context-questions-and-issues) instead of the [Research findings and themes](https://github.com/ipfs/browser-design-guidelines/blob/master/README.md#research-findings-and-themes)?

**Comment by jkosem** [comment]
<img width="1527" alt="Screenshot 2019-12-05 at 13 26 15" src="https://user-images.githubusercontent.com/495102/70235325-0ae1e900-1763-11ea-95cd-ee7a067a7511.png">

Format slightly changed/edited:

Decide on the Decider which is most likely Dietrich

1. 10min of presenting key themes and findings
2. No conversation allowed, but while listening to the key themes and findings read out, you should write down what resonates with you as (1)  reasons to design it, and (2) what they hear as reasons to not design it, on red sticky notes.
3. The red and green post-its are placed below each finding.
4. If there are too many reds, you can probably stop here
5. Vote/prioritise each, 1. by importance, 2. will be biggest challenges
6. Depending on the circumstances you could place the top voted on an effort/impact scale
7. Let everyone individually speak their opinion on whether it should be done or not, but the Decider makes the call

I reckon we can do it in 30-40 minutes or so

**Comment by jkosem** [comment]
@ericronne I'll send an invite for you in a minute by email with the details.

**Comment by jkosem** [comment]
Edited the format a bit so deleted the previous

The board we're going to be working on looks like this
<img width="1337" alt="Screenshot 2019-12-06 at 13 59 35" src="https://user-images.githubusercontent.com/495102/70324844-dc324400-1830-11ea-9423-32d3a21181c3.png">

The format slightly adjusted and clarified looks like this:
1. Decide on the Decider which is most likely Dietrich
2. 10min of presenting key themes and findings. Jim will read these out.
3. No conversation allowed, but while listening to the key themes and findings read out by Jim, Eric and Dietrich should write down what resonates with them as 1.) reasons to design it (green post-it), and 2.) what they hear as reasons to not design it (red post-it).
4. The red and green post-its are placed below each finding by Eric and Dietrich.
5. If there are too many reds, you can probably stop there
6. Vote/prioritise each, 1.) by importance, and 2.) what will be biggest challenges
7. Depending on the circumstances you could place the top voted on an effort/impact scale
8. Let everyone individually speak their opinion on whether it should be done or not, but the Decider makes the call

**Comment by jkosem** [comment]
I'm waiting for a rocket and thumbs up emoji

**Comment by jkosem** [comment]
Thanks @ericronne and @autonome, hope that was useful, was for me to get your thinking around the findings and see where the use cases and design might go from there.

**Comment by ericronne** [comment]
Indeed it was! Thanks for the good prep and Wise moderation. Can't wait to see the report!
