### ISSUE TITLE
W3C use-cases examples

### ISSUE THREAD

**Issue by jkosem** [ipfs/browser-design-guidelines#54]
These the ones?
https://www.w3.org/2012/webcrypto/wiki/Use_Cases

**Comment by autonome** [comment]
* https://usecases.responsiveimages.org/
* https://w3c-webmob.github.io/installable-webapps/
* https://www.w3.org/2001/sw/sweo/public/UseCases/
* https://w3c.github.io/webrtc-nv-use-cases/
* https://w3c-lbd-cg.github.io/lbd/UseCasesAndRequirements/
* https://lists.w3.org/Archives/Public/public-blockchain/2017Mar/att-0021/W3CBlockchainCGUseCases.pdf
* http://docs.opengeospatial.org/dp/15-074/15-074.html
* Notes of a conversation about use-cases: https://w3c-ccg.github.io/meetings/2019-02-12/#topic-4
* https://w3c-ccg.github.io/did-use-cases/
* https://tools.ietf.org/html/draft-yasskin-http-origin-signed-responses-08
* https://github.com/w3c/vc-use-cases

**Comment by autonome** [comment]
Updating the title - the idea here was to collect examples of how use-cases are written up in standardization process, not to be specific to p2p.

That said, I did poke around for p2p work in w3c a while back and did not find much.

These couple of early notes, mostly referencing Freenet:

* https://www.w3.org/2001/04/w3c-p2p/
* https://www.w3.org/2001/04/w3c-p2p/comparison

Later 2000s W3C activity re P2P was all about WebRTC:

* https://w3c.github.io/webrtc-pc/
* This SO thread has a ton of references: https://stackoverflow.com/questions/7022383/how-can-i-make-a-browser-to-browser-peer-to-peer-connection

And in contemporary times, work on WebRTC-QUIC / WebRTC-NV:

* https://w3c.github.io/webrtc-quic/
* https://github.com/w3c/webrtc-nv-use-cases/issues/15

**Comment by jkosem** [comment]
I think this one (https://usecases.responsiveimages.org/) might be the most relevant. What I'm thinking is a walk through more like this (https://w3c-webmob.github.io/installable-webapps/) though which is clearer to read.

So in Use Case 1 "Share file from browser", it would go through what the situation is with the user, how some things that are similar work today and then screens showing proposed ideas?
