### ISSUE TITLE
Firefox and Brave shields subsection/sidenote/addendum

### ISSUE THREAD

**Issue by jkosem** [ipfs/browser-design-guidelines#57]
<img width="739" alt="Screenshot 2019-12-04 at 13 14 17" src="https://user-images.githubusercontent.com/495102/70141780-07356000-1698-11ea-90c8-f0480f7bd2b7.png">

This would be featured in an out-of-scope area as well? It's actually covered [here](https://github.com/ipfs/browser-design-guidelines/wiki/Firefox-70.0.1)

**Comment by jkosem** [comment]
Likewise Brave's in-depth forray into counter-surveillance
<img width="911" alt="Screenshot 2019-12-04 at 13 18 10" src="https://user-images.githubusercontent.com/495102/70142032-a8bcb180-1698-11ea-90d0-14adbc70270d.png">

**Comment by autonome** [comment]
We can have these represented as a subsection/sidenote/addendum in the Location Bar Review.

When we write up the final recommendations for visual treatment of the address bar for ipfs:// content, we need to note how these vendors should handle these pieces of UI.

All of the implementation infrastructure for tracker identification and blocking is HTTP-centric, so most of the functionality in these interfaces doesn't make any sense in the context of ipfs:// content.

We'll need to do an analysis of tracking methods or potential with IPFS content requests, and provide a recommendation based on the outcome.
