### ISSUE TITLE
Report to share

### ISSUE THREAD

**Issue by jkosem** [ipfs/browser-design-guidelines#59]
PDF with graphics with callouts as a the final deliverable

**Comment by jkosem** [comment]
@autonome If you can think of anything else in terms of requirements let me know. I imagine it's somthing like...

_As a commisioner of a number of months of research and design
So that I can share with the company at large and in external presentations
I need a PDF including the top level research findings, graphics of the design with callouts labelling what is going on and final recommendations for where to take P2P with IPFS_

**Comment by jkosem** [comment]
To keep up the markdown madness going, and in the interest of going fully web and OSS, I dug up this https://github.com/hakimel/reveal.js/ which might work as well for the final presentation.

Alternately, a Github page?

**Comment by jkosem** [comment]
or Gitbook https://www.gitbook.com/

**Comment by jkosem** [comment]
Actually it seems HackMD might be the best way as it does slides, has collab functionality and comments. Here's a test one.
https://hackmd.io/@jkosem/S1DyJtL6S#/

**Comment by jkosem** [comment]
And it seems HackMD uses reveal.js. Yay.

**Comment by autonome** [comment]
I've used Hackmd for slides, is good for presentations but not for report building. Use Sketch/Figma or whatever tool you're most comfortable with for shipping the final report as a PDF as we talked about this morning. The PDF can be then used for presentations, shared on the blog and the master stored in this repo, updated from source graphics tool.

**Comment by jkosem** [comment]
Gotcha. I've seen this.

If you can, send an example of if you have something in particular in mind. Othewise Eric sent me this https://docs.google.com/presentation/d/1WrHfc14o_5ziJ0g6okqG9N73XEUzhBXQuD_x_Zut7q8/edit?ts=5de67f59#slide=id.p1 which I can follow.

Also I can just do it in Gdocs if that's better for you/PL?

**Comment by autonome** [comment]
We covered today, moving all work for final report to the deck.
