### ISSUE TITLE
Browsers in S America and Asia show bandwidth?

### ISSUE THREAD

**Issue by jkosem** [ipfs/browser-design-guidelines#69]

**Comment by autonome** [comment]
This is a good article with screenshots of a number of mobile browsers - where and how they communicate data consumption:

https://beebom.com/best-data-saving-android-browsers/

A little old, but still holds up as you can see by current browser market share in Asia: Chrome dominates, but a bunch of the others are basically non-existent in US/EU markets: Samsung Internet, Opera, UC Browser.

https://gs.statcounter.com/browser-market-share/all/asia

## Firefox Lite

Designed specifically for Asia, available only in specific countries' Android Play Stores. Many of the features are either directly related to data consumption management (Turbo Mode) or indirectly: Pre-loaded content and pre-configured services mean content delivery shifts a subset of ongoing network activity to app updates.

https://support.mozilla.org/en-US/products/firefox-lite/get-started
