### ISSUE TITLE
Can this repo be archived?

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/browser-design-guidelines#73]
Is it still used?

**Comment by hsanjuan** [comment]
/remind me to act in 3 days

**Comment by jkosem** [comment]
@autonome ^^ ?

**Comment by jkosem** [comment]
> Is it still used?

We link to it with the current [Mobile Design Guidelines](https://github.com/ipfs/mobile-design-guidelines) and have shared with other community members.

**Comment by jkosem** [comment]
@hsanjuan If you could wait a couple of weeks, ideally until we wrap up the [Mobile Design Guidelines](https://github.com/ipfs/mobile-design-guidelines) that would be great.

**Comment by autonome** [comment]
We're going to publish these guidelines from here, so should not be archived.

**Comment by hsanjuan** [comment]
Thanks!
